<?php

namespace AppBundle\Repository;


use AppBundle\Entity\Balances;
/**
 * BalanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BalancesRepository extends \Doctrine\ORM\EntityRepository
{
	public function deleteAll() {
		$em = $this->getEntityManager()
			->createQuery('DELETE FROM AppBundle:Balances');
		return $em->execute(); ;

	}

	public function getBalance() {

		$qb = $this->createQueryBuilder('b')
			->andWhere('b.isActive = true')
			->select('SUM(b.priceBtc) as  priceBTC, SUM(b.priceUsd) as  priceUSD')
			->getQuery()
            ->getOneOrNullResult();

		return $qb;


	}

}