<?php

namespace AppBundle\Repository;

/**
 * cryptoCurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CryptoCurrencyRepository extends \Doctrine\ORM\EntityRepository
{
}
