<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository as Repository;
/**
 * DepositStatisticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepositMonthRepository extends Repository
{



}
