<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository as Repository;
/**
 * cryptoCurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepositRepository extends Repository
{
	public function groupDepositByMonth(){
		$stmt = $this->getEntityManager()
			->getConnection()
			->prepare('SELECT d.currency, d.currency_name, SUM(d.amount)
 			as sum_amount, d.from_in, date_trunc(\'month\', get_date) as month FROM deposit d 
 			where d.is_active = true
 			GROUP BY d.currency, d.currency_name, d.from_in, date_trunc(\'month\', get_date)');
		$stmt->execute();
		$result = $stmt->fetchAll();
		return $result;
	}

}
