<?php

namespace AppBundle\Repository;

/**
 * BalanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderHistoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function getOrderStatistic() {
		$qb = $this->createQueryBuilder('oh')
			->select('oh.stockExchange',
				'oh.exchange',
				'SUM(CASE 	WHEN oh.orderType = \'sell\' THEN oh.priceUsd	ELSE -oh.priceUsd END) as sumUsd',
				'SUM(CASE	WHEN oh.orderType = \'sell\' THEN oh.price - COALESCE(oh.commission,0) ELSE -oh.price - COALESCE(oh.commission,0) END) as sumCrypto',
				'SUM(CASE	WHEN oh.orderType = \'sell\' THEN oh.quantity ELSE 0 END) as sellCount',
				'SUM(CASE	WHEN oh.orderType = \'buy\' THEN oh.quantity	ELSE 0 END) as buyCount')
			->groupBy('oh.stockExchange', 'oh.exchange')
			->getQuery()
			->getResult();
		return $qb;
	}
}