<?php

namespace AppBundle\Repository;


/**
 * BalanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderStatisticRepository extends \Doctrine\ORM\EntityRepository
{
	public function setNoActive(){
		$qb = $this->createQueryBuilder('os')
			->update('AppBundle:OrderStatistic', 'os')
			->set('os.isActive', 'false')
			->where('os.isActive = true')
			->getQuery()
			->getResult();
		return $qb;
	}

}