<?php

namespace AppBundle\Repository;

use Symfony\Component\Validator\Constraints\DateTime;


/**
 * BalanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatisticRepository extends \Doctrine\ORM\EntityRepository
{
	public function getColumn(array $columns, $idUser = 1) {
		$alias = 's';
		foreach ($columns as &$column){
			$column = $alias.'.'.$column;
		}
		$qb = $this->createQueryBuilder('s')
			->select(implode(', ',$columns))
			->andWhere('s.idUsers = :IDUSER')->setParameter('IDUSER', $idUser)
			->orderBy('s.addDate', 'ASC')
			->getQuery()
			->getResult();

		$res = [];
		foreach ($qb as $k =>$one){
			foreach ($one as $k=>$v){
				if(is_a($v,'DateTime')){
					$res[$k][] = $v->format('d.m.Y H:m');
				}else{
					$res[$k][] = $v;
				}

			}
		}
		return $res;


	}

}