<?php

namespace AppBundle\Repository;

use Symfony\Component\Validator\Constraints\DateTime;


/**
 * BalanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatisticRepository extends \Doctrine\ORM\EntityRepository
{
	public function getColumn(array $columns) {
		$alias = 's';
		foreach ($columns as &$column){
			$column = $alias.'.'.$column;
		}
		$qb = $this->createQueryBuilder('s')
			->select(implode(', ',$columns))
			->getQuery()
			->getResult();

		$res = [];
		foreach ($qb as $k =>$one){
			foreach ($one as $k=>$v){

				dump(is_a($v,'DateTime'));
				if(is_a($v,'DateTime')){
					dump($v);
					$res[$k][] = $v->format('m.d.Y H:m');
				}else{
					$res[$k][] = $v;
				}

			}
		}
		return $res;


	}

}