<?php

namespace AppBundle\Repository;


/**
 * BalanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatisticRepository extends \Doctrine\ORM\EntityRepository
{
	public function getColumn(array $columns) {
		$alias = 's';
		foreach ($columns as &$column){
			$column = $alias.'.'.$column;
		}
		$qb = $this->createQueryBuilder('s')
			->select(implode(', ',$columns))
			->getQuery()
			->getResult();

		$res = [];
		foreach ($qb as $k =>$one){
			foreach ($one as $k=>$v){
				$res[$k][] = $v;
			}
		}
		return $res;


	}

}